Repository unvt/charites, pull requests merged in 2021-11, with the labels that each got.

#34 fixed bug for init command
  README.md
  src/cli.ts
Labels: bug

#38 fixed a url bug of metadata.json importing
  src/lib/tileinfo-importer/metadata-importer.ts
  test/data/init/init_metadata.yml
Labels: bug

#49 separate cli.ts to multiple files for each command.
  README.md
  package.json
  src/cli.ts
  src/cli/build.ts
  src/cli/convert.ts
  src/cli/error.ts
  src/cli/index.ts
  src/cli/init.ts
  src/cli/serve.ts
  src/commands/build.ts
  tsconfig.json
Labels: enhancement

#55 Editing Readme
  README.md
Labels: documentation

#64 added CONTRIBUTING.md and Issue/PR templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#65 updated copyright in LICENSE file
  LICENSE
Labels: documentation
